kind: # https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: default
data:
  my_key: my_value
  my_new_key: my_new_value
---

